name: Test Python

on: [push, pull_request]

jobs:
  test_python:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: ['3.7', '3.11']
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go 1.x
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.12
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.version }}
      - name: Install go dependencies
        run: go get github.com/keller-mark/esbuild-py
      - name: Build package
        run: |
          python setup.py bdist_wheel
          python setup.py sdist
      - name: Install (non-editable)
        run: pip install .[dev]
      - name: Run unit tests
        run: pytest